---
title: "Homework 3"
author: "Pa"
date: "2022-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Q1 writing function named "stock_advice" to tell whether should sell stocks under certain condition using if else conditional statement 
stock_advice<- function (value, day1,day2,day3){
  average<-mean(c(day1,day2,day3)) 
  if (average>value) 
    return("sell")
else if (average<value) 
  return("buy ")
else if (average == value)
  return("watch")
}
stock_advice(12.11,10.39,15.98,13.96) 
```

```{r}
#Q2
x<-c(3,6,12,17,19,33,24,21,10,8,5) 
for (i in 1:length(x)){
  if (x[i]<15){
    x[i]=x[i]-1
  }
  
}
print(x)
```

```{r}
#Q3a creating a tables 
Name<-c("Jacke", "Jerry", "Emma", "Andy", "Jayde", "Lynn","Liam")
Education<- c("Master","Master","Master","Bachelor","Bachelor", "PhD","PhD")
Salary<- c(20000, 20000,20000,30000,10000,70000,70000)
mydata<-data.frame(Name,Education,Salary)
print(mydata)
#Q3b creating loop and conditional statement 
for (row in 1:nrow(mydata)){
  if(mydata[row, "Education"]=="Bachelor"){
    mydata[row,"Salary"]=mydata[row,"Salary"]+ 1000
  }

  else if(mydata[row,"Education"]=="Master"){
    mydata[row,"Salary"]=mydata[row,"Salary"]+2000
  }

  else{
    mydata[row,"Salary"]=mydata[row,"Salary"]+3000
  }
}
print(mydata)
```

```{r}
#Q4  
treatment=NULL
Baseline<-c(100,110,109,99,103,101,125,130)
Follow_up<-c(105,100,102,105,100,97,108,120)
for(i in 1:length(Baseline)){
  if (Baseline[i]> Follow_up[i]){
    treatment[i]= "no treatment needed"
  }
  else if (Baseline[i]< Follow_up[i]){
    treatment[i]= "more treatment needed"
  }
  else {print("to be determined")}
}
```

```{r}
#Q5
matrix_sum=0
M<-function(x){   
  for (i in 1:nrow(x))
   {
     for (j in 1:ncol(x))
     {
       matrix_sum<- matrix_sum+x[i,j]
     }
  }
  return(matrix_sum)
}
A<-matrix(c(36,51,40,39,78,62,22,37,52), nrow=3, byrow=TRUE)
M(A)
```

