---
title: "Worksheet11"
author: "Pa"
date: "2022-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
#Q1
#H0: mu=42  Ha: mu!=42
#one sample test 
t.test(x=c(43, 44, 37, 49, 38, 42, 44, 51, 35
), mu=42, alternative = "two.sided")

#fail to reject H0. There is no evidence to prove that the mean students’ guess is significantly different from Wei’s actual age

```

```{r}
#Q2
#H0: mu(Bakery)=mu(Pizza)  Ha:mu(Bakery)!=mu(Pizza)
Store1<-Startup %>%
  filter(!is.na(Cost))
t.test(Cost~Store, data= Store1, alterantive= "two,side")

#Fail to reject H0. There is no evidence to support that opening a Pizzeria store and opening a Bakery store costs differently.

Store1%>%
  group_by(Store)%>%
  summarize(avecost=mean(Cost), secost=sd(Cost)/sqrt(length(Cost)), tvalue=qt(1-0.05/2, length(Cost)-1))%>%
  ggplot(aes(x=Store, y= avecost))+geom_point()+geom_errorbar(aes(ymin=avecost-secost*tvalue,ymax=avecost+secost*tvalue))+ylim(c(0,120))

```

```{r}
#Q3
#H0: mu(wet)=mu(regular) Ha: mu(wet)>mu(regular)
t.test(Velocity~Suit, data = swimming, alternative="less", paired= TRUE)

#Reject H0. There is evidence to support the claim that the average velocity from the wetsuit is significantly higher than the average velocity from the refular suit
```

